import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Netlytics V10 — Professional Report Generator
 * Generates a "Proof of Service" PDF for legal/ISP auditing purposes.
 */

export const generatePDFReport = (user, logs) => {
    const doc = new jsPDF();
    const timestamp = new Date().toLocaleString();
    const dateStr = new Date().toISOString().split('T')[0];

    // --- Header ---
    doc.setFillColor(5, 5, 16); // Dark background
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(22);
    doc.setTextColor(0, 243, 255); // Neon Cyan
    doc.text('NETLYTICS ZENITH', 15, 25);
    
    doc.setFontSize(10);
    doc.setTextColor(188, 19, 254); // Neon Purple
    doc.text('NETWORK AUDIT & PROOF OF SERVICE REPORT', 15, 33);

    // --- Meta Info ---
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Generated: ${timestamp}`, 140, 25);
    doc.text(`User ID: ${user.id.slice(0, 8)}`, 140, 31);

    // --- Summary Section ---
    doc.setFontSize(14);
    doc.setTextColor(33, 33, 33);
    doc.text('EXECUTIVE SUMMARY', 15, 55);
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 58, 195, 58);

    // Flatten all tests for calculation
    const allTests = logs.flatMap(day => day.tests || []);
    if (allTests.length === 0) {
        doc.setFontSize(14);
        doc.setTextColor(239, 68, 68);
        doc.text('No performance telemetry found in the selected range.', 15, 60);
        doc.save(`Netlytics_Audit_Empty_${dateStr}.pdf`);
        return;
    }

    const avgDl = allTests.reduce((a, b) => a + (b.download || 0), 0) / allTests.length;
    const avgUl = allTests.reduce((a, b) => a + (b.upload || 0), 0) / allTests.length;
    const downloads = allTests.map(t => t.download || 0);
    const maxDl = downloads.length > 0 ? Math.max(...downloads) : 0;
    const avgPing = allTests.reduce((a, b) => a + (b.ping || 0), 0) / allTests.length;

    // Summary Cards
    doc.setFontSize(10);
    doc.text(`Total Probes Analyzed: ${allTests.length}`, 15, 68);
    doc.text(`Average Download: ${avgDl.toFixed(2)} Mbps`, 15, 75);
    doc.text(`Average Upload: ${avgUl.toFixed(2)} Mbps`, 15, 82);
    doc.text(`Peak Download: ${maxDl.toFixed(2)} Mbps`, 100, 75);
    doc.text(`Mean Latency: ${avgPing.toFixed(1)} ms`, 100, 82);

    // --- Detailed Test Logs ---
    doc.setFontSize(14);
    doc.text('DETAILED TELEMETRY LOG', 15, 100);
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 103, 195, 103);

    const tableRows = allTests.slice(0, 50).map(test => [
        new Date(test.timestamp || Date.now()).toLocaleString(),
        `${test.download || 0} Mbps`,
        `${test.upload || 0} Mbps`,
        `${test.ping || 0} ms`,
        test.is_auto ? 'AUTO' : 'USER',
        (test.profile || '—').toUpperCase()
    ]);

    autoTable(doc, {
        startY: 110,
        head: [['Timestamp', 'Download', 'Upload', 'Ping', 'Mode', 'Profile']],
        body: tableRows,
        headStyles: { fillColor: [5, 5, 16], textColor: [0, 243, 255] },
        bodyStyles: { fontSize: 9 },
        alternateRowStyles: { fillColor: [245, 245, 245] }
    });

    // --- Footer ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('This report is generated by Netlytics Zenith. The data provided is for informational purposes and intended to serve as a proof of service log.', 15, 285);
        doc.text(`Page ${i} of ${pageCount}`, 180, 285);
    }

    doc.save(`Netlytics_Audit_${dateStr}.pdf`);
};
